### ISSUE TITLE
Problem Statement

### ISSUE THREAD

**Issue by rnorouziani** [rnorouziani/Helmholtz-Coil-Current-Calculator-CAS741#1]
Dear Dr.  Smith,
Please review my [problem statement](https://github.com/rnorouziani/Helmholtz-Coil-Current-Calculator-CAS741/blob/main/docs/ProblemStatementAndGoals/ProblemStatement.pdf).

Thank you so much.

**Comment by smiths** [comment]
Feedback:

- what is the type of the desired magnetic field?  Is it just the strength of the field, or is it the shape of the field?
- rather than "in order to", just say "to"
- are you building an application, or a library? (your stretch goals imply an app, but make it explicit)
- what input is the joystick control changing?

The project sounds interesting.  It is approved.  :smile:
